service:
  name: todolist

plugins: 
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom: 
  webpack: 
    webpackConfig: ./webpack.config.js
    includeModules: true

  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider: 
  name: aws
  runtime: nodejs14.x
  regions: us-east-1

functions: 
  postTodo: 
    handler: src/functions/postTodo.handle
    events: 
      - http: 
          path: /todos/{userid}
          method: POST
          cors: true
      # - http: 
      #     path: /todos/{userid}
      #     method: POST
      #     cors: true

  getTodo: 
    handler: src/functions/getTodo.handle
    events: 
      - http: 
          path: /todos/{userid}
          method: GET
          cors: true

resources: 
  Resources:
    dbTodoUsers:
      Type: AWS::DynamoDB::Table
      Properties: 
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: todo_list
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
